"""Added creator_email to user table

Revision ID: 1c185e8da3b6
Revises: ec390e977fa2
Create Date: 2021-11-18 23:29:34.475419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c185e8da3b6'
down_revision = 'ec390e977fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('creator_email', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_creator_email'), 'user', ['creator_email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_creator_email'), table_name='user')
    op.drop_column('user', 'creator_email')
    # ### end Alembic commands ###
