"""Changed PK column name for itn_meta to id instead itn

Revision ID: 2787e925bb27
Revises: 
Create Date: 2021-11-25 09:23:10.205150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2787e925bb27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itn_schedule',
    sa.Column('itn', sa.String(length=33), nullable=False),
    sa.Column('utc', sa.DateTime(), nullable=False),
    sa.Column('consumption_vol', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('forecast_vol', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['itn'], ['itn_meta.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('itn', 'utc')
    )
    op.drop_index('ix_itn_meta_itn', table_name='itn_meta')
    op.create_index(op.f('ix_itn_meta_id'), 'itn_meta', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itn_meta_id'), table_name='itn_meta')
    op.create_index('ix_itn_meta_itn', 'itn_meta', ['id'], unique=False)
    op.drop_table('itn_schedule')
    # ### end Alembic commands ###
