"""initial

Revision ID: 2e024933391e
Revises: 
Create Date: 2021-12-04 15:50:00.490175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e024933391e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('address_line', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_address_line'), 'address', ['address_line'], unique=False)
    op.create_index(op.f('ix_address_city'), 'address', ['city'], unique=False)
    op.create_index(op.f('ix_address_id'), 'address', ['id'], unique=False)
    op.create_index(op.f('ix_address_postal_code'), 'address', ['postal_code'], unique=False)
    op.create_table('contractor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('eik', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractor_eik'), 'contractor', ['eik'], unique=True)
    op.create_index(op.f('ix_contractor_id'), 'contractor', ['id'], unique=False)
    op.create_index(op.f('ix_contractor_name'), 'contractor', ['name'], unique=False)
    op.create_table('itn_meta',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('erp', sa.String(), nullable=True),
    sa.Column('load_type', sa.String(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itn_meta_erp'), 'itn_meta', ['erp'], unique=False)
    op.create_index(op.f('ix_itn_meta_id'), 'itn_meta', ['id'], unique=True)
    op.create_index(op.f('ix_itn_meta_load_type'), 'itn_meta', ['load_type'], unique=False)
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('contractor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_end_date'), 'contract', ['end_date'], unique=False)
    op.create_index(op.f('ix_contract_id'), 'contract', ['id'], unique=True)
    op.create_index(op.f('ix_contract_start_date'), 'contract', ['start_date'], unique=False)
    op.create_table('itn_schedule',
    sa.Column('itn', sa.String(length=33), nullable=False),
    sa.Column('utc', sa.DateTime(), nullable=False),
    sa.Column('consumption_vol', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('forecast_vol', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['itn'], ['itn_meta.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('itn', 'utc')
    )
    op.create_table('sub_contract',
    sa.Column('itn', sa.String(length=33), nullable=False),
    sa.Column('price', sa.Numeric(precision=8, scale=7), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['itn'], ['itn_meta.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('itn', 'start_date', 'end_date')
    )
    op.create_index(op.f('ix_sub_contract_end_date'), 'sub_contract', ['end_date'], unique=False)
    op.create_index(op.f('ix_sub_contract_price'), 'sub_contract', ['price'], unique=False)
    op.create_index(op.f('ix_sub_contract_start_date'), 'sub_contract', ['start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sub_contract_start_date'), table_name='sub_contract')
    op.drop_index(op.f('ix_sub_contract_price'), table_name='sub_contract')
    op.drop_index(op.f('ix_sub_contract_end_date'), table_name='sub_contract')
    op.drop_table('sub_contract')
    op.drop_table('itn_schedule')
    op.drop_index(op.f('ix_contract_start_date'), table_name='contract')
    op.drop_index(op.f('ix_contract_id'), table_name='contract')
    op.drop_index(op.f('ix_contract_end_date'), table_name='contract')
    op.drop_table('contract')
    op.drop_index(op.f('ix_itn_meta_load_type'), table_name='itn_meta')
    op.drop_index(op.f('ix_itn_meta_id'), table_name='itn_meta')
    op.drop_index(op.f('ix_itn_meta_erp'), table_name='itn_meta')
    op.drop_table('itn_meta')
    op.drop_index(op.f('ix_contractor_name'), table_name='contractor')
    op.drop_index(op.f('ix_contractor_id'), table_name='contractor')
    op.drop_index(op.f('ix_contractor_eik'), table_name='contractor')
    op.drop_table('contractor')
    op.drop_index(op.f('ix_address_postal_code'), table_name='address')
    op.drop_index(op.f('ix_address_id'), table_name='address')
    op.drop_index(op.f('ix_address_city'), table_name='address')
    op.drop_index(op.f('ix_address_address_line'), table_name='address')
    op.drop_table('address')
    # ### end Alembic commands ###
