"""Added relation betwenn schedule and meta

Revision ID: 8af5ffbbe8e6
Revises: 2787e925bb27
Create Date: 2021-11-25 09:51:16.949804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8af5ffbbe8e6'
down_revision = '2787e925bb27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
