"""Added relation between contractor and address

Revision ID: 9882e86c75f7
Revises: 1c185e8da3b6
Create Date: 2021-11-24 16:47:27.470138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9882e86c75f7'
down_revision = '1c185e8da3b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contractor', sa.Column('address_id', sa.Integer(), nullable=True))
    op.drop_index('ix_contractor_address', table_name='contractor')
    op.create_foreign_key(None, 'contractor', 'address', ['address_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('contractor', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contractor', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contractor', type_='foreignkey')
    op.create_index('ix_contractor_address', 'contractor', ['address'], unique=False)
    op.drop_column('contractor', 'address_id')
    # ### end Alembic commands ###
