"""Added last_seen and last_updated in user table

Revision ID: ec390e977fa2
Revises: 296c9b65cf52
Create Date: 2021-11-18 22:53:38.146062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec390e977fa2'
down_revision = '296c9b65cf52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_updated')
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###
